databases:
  - name: koinsave-db
    plan: free

services:
  - type: web
    name: koinsave-api
    env: node
    plan: free
    buildCommand: |
      npm install --include=dev
      npm run build
      npx prisma generate --schema prisma/schema.postgres.prisma
      npx prisma db push --schema prisma/schema.postgres.prisma
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: koinsave-db
          property: connectionString